Repository tropicsquare/libtropic, pull requests merged in 2025-09, with the labels that each got.

#246 ETR01SDK-222: Add compiler and linker flags for unused sections removal
  CHANGELOG.md
  CMakeLists.txt
  vendor/trezor_crypto/CMakeLists.txt
Labels: enhancement

#255 ETR01SDK-225: Missing const for lt_r_ mem_data_write
  CHANGELOG.md
  include/libtropic.h
  include/lt_l3.h
  src/libtropic.c
  src/lt_l3.c
Labels: bug

#261 ETR01-SDK-90: Add TS04 control script
  scripts/test_runner/ts04_control.py
Labels: scripts

#263 Add silicon revision cmake option
  CHANGELOG.md
  CMakeLists.txt
Labels: functional tests, feature

#269 ETR01-SDK-217: Fix lt random bytes so it takes lt_handle_t as argument
  CHANGELOG.md
  examples/lt_ex_macandd.c
  src/libtropic_l3.c
  src/lt_random.c
  src/lt_random.h
  tests/functional/lt_test_ire_write_i_config.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_mac_and_destroy.c
  tests/functional/lt_test_rev_mcounter.c
  tests/functional/lt_test_rev_ping.c
  tests/functional/lt_test_rev_r_mem.c
  tests/functional/lt_test_rev_random_value_get.c
  tests/functional/lt_test_rev_write_r_config.c
Labels: enhancement

#268 WIP: ETR01SDK-238: Change parameter checking
  CHANGELOG.md
  examples/lt_ex_hello_world_separate_API.c
  examples/lt_ex_hw_wallet.c
  examples/lt_ex_macandd.c
  examples/lt_ex_show_chip_id_and_fwver.c
  include/libtropic.h
  include/libtropic_l3.h
  src/libtropic.c
  src/libtropic_l3.c
  tests/functional/lt_test_rev_ecc_key_generate.c
  tests/functional/lt_test_rev_ecc_key_store.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_get_info_req_bootloader.c
  tests/functional/lt_test_rev_get_log_req.c
  tests/functional/lt_test_rev_r_mem.c
Labels: enhancement

#274 Fix: SPI data printing
  src/lt_l1.c
Labels: bug

#275 test(lt_test_rev_get_info_req_bootloader): allow empty bank for ACAB
  tests/functional/lt_test_rev_get_info_req_bootloader.c
Labels: functional tests

#273 ETR01SDK-250: Add support for C++ linkage
  hal/port/unix/libtropic_port_unix_spi.h
  hal/port/unix/libtropic_port_unix_tcp.h
  hal/port/unix/libtropic_port_unix_usb_dongle.h
  include/bits.h
  include/libtropic.h
  include/libtropic_common.h
  include/libtropic_examples.h
  include/libtropic_functional_tests.h
  include/libtropic_l2.h
  include/libtropic_l3.h
  include/libtropic_logging.h
  include/libtropic_macros.h
  include/libtropic_port.h
  include/tropic01_application_co.h
  include/tropic01_bootloader_co.h
  src/lt_aesgcm.h
  src/lt_asn1_der.h
  src/lt_crc16.h
  src/lt_ecdsa.h
  src/lt_ed25519.h
  src/lt_hkdf.h
  src/lt_hmac_sha256.h
  src/lt_l1.h
  src/lt_l1_port_wrap.h
  src/lt_l2_api_structs.h
  src/lt_l2_frame_check.h
  src/lt_l3_api_structs.h
  src/lt_l3_process.h
  src/lt_random.h
  src/lt_sha256.h
  src/lt_x25519.h
Labels: enhancement

#277 ETR01SDK-263: rework switches for crypto providers
  .gitlab-ci.yml
  CHANGELOG.md
  CMakeLists.txt
  hal/crypto/trezor_crypto/lt_crypto_trezor_aesgcm.c
  hal/crypto/trezor_crypto/lt_crypto_trezor_ecdsa.c
  hal/crypto/trezor_crypto/lt_crypto_trezor_ed25519.c
  hal/crypto/trezor_crypto/lt_crypto_trezor_hmac_sha256.c
  hal/crypto/trezor_crypto/lt_crypto_trezor_sha256.c
  hal/crypto/trezor_crypto/lt_crypto_trezor_x25519.c
  include/libtropic_common.h
  src/lt_aesgcm.h
  src/lt_hkdf.c
  src/lt_sha256.h
  tropic01_model/CMakeLists.txt
Labels: enhancement

#282 ETR01SDK-273: add docs structure, enhance names of topics
  docs/doxygen/Doxyfile.in
  docs/doxygen/mainpage.md
  include/libtropic.h
  include/libtropic_examples.h
  include/libtropic_functional_tests.h
  include/libtropic_l2.h
  include/libtropic_l3.h
  include/libtropic_port.h
  src/lt_l1.h
  src/lt_l1_port_wrap.h
  src/lt_l2_frame_check.h
  src/lt_l3_process.h
Labels: documentation

#276 ETR01SDK-220: Fix CRC handling on startup
  include/libtropic_common.h
  src/libtropic.c
  src/libtropic_l2.c
  src/lt_crc16.c
Labels: bug

#285 ETR01SDK-281: add debug message type to test runner
  scripts/test_runner/lt_test_runner/lt_test_runner.py
Labels: bug

#290 ETR01SDK-276: Enhance Get Started->Compiling as a Static Archive
  docs/get_started/integrating_libtropic/adding_to_project.md
  docs/get_started/integrating_libtropic/compile_as_static_archive.md
  docs/get_started/integrating_libtropic/compile_as_static_library.md
  docs/get_started/integrating_libtropic/index.md
  mkdocs.yml
Labels: documentation

#292 ETR01SDK-265: refactor macros for reboot types
  CHANGELOG.md
  examples/lt_ex_fw_update.c
  examples/lt_ex_hw_wallet.c
  examples/lt_ex_show_chip_id_and_fwver.c
  include/libtropic.h
  include/libtropic_common.h
  include/libtropic_functional_tests.h
  src/libtropic.c
  src/lt_l1.c
  src/lt_l2_api_structs.h
  tests/functional/lt_test_rev_get_info_req_bootloader.c
  tests/functional/lt_test_rev_get_log_req.c
  tests/functional/lt_test_rev_resend_req.c
  tests/functional/lt_test_rev_startup_req.c
Labels: enhancement

#294 ETR01SDK-274: Refactor doc For contributors->Adding a new embedded platform
  docs/get_started/examples/index.md
  docs/get_started/examples/irreversible_examples.md
  docs/get_started/examples/reversible_examples.md
  mkdocs.yml
Labels: documentation
