Repository tropicsquare/libtropic, pull requests merged in 2025-08, with the labels that each got.

#186 refactor: moved device structure to libtropic_port.h
  CHANGELOG.md
  include/libtropic_common.h
  include/libtropic_port.h
Labels: enhancement

#189 refactor lt_test_rev_read_chip_id and add new helpers
  CHANGELOG.md
  include/libtropic.h
  include/libtropic_common.h
  src/libtropic.c
  tests/functional/lt_test_rev_read_chip_id.c
Labels: functional tests

#190 feat(ecdsa_sign, eddsa_sign): test signing with empty slots
  include/libtropic_functional_tests.h
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
Labels: functional tests

#184 Add Sleep_Req test
  CMakeLists.txt
  include/libtropic_functional_tests.h
  tests/functional/lt_test_rev_sleep_req.c
Labels: functional tests

#194 Refactor: print cleanup return value directly in lt_assert_fail_handler.
  tests/functional/lt_test_common.c
  tests/functional/lt_test_rev_ecc_key_generate.c
  tests/functional/lt_test_rev_ecc_key_store.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_erase_r_config.c
  tests/functional/lt_test_rev_r_mem.c
  tests/functional/lt_test_rev_write_r_config.c
Labels: enhancement, functional tests

#182 Add startup req test
  .github/workflows/integration_tests.yml
  CMakeLists.txt
  include/libtropic_functional_tests.h
  tests/functional/lt_test_rev_startup_req.c
  tests/model_based_project/README.md
Labels: functional tests

#160 Refactor examples
  CHANGELOG.md
  examples/lt_ex_hello_world.c
  examples/lt_ex_hello_world_separate_API.c
  examples/lt_ex_hw_wallet.c
  examples/lt_ex_macandd.c
  include/libtropic_examples.h
Labels: examples

#187 Fix STM32 compilation errors
  CHANGELOG.md
  examples/lt_ex_fw_update.c
  examples/lt_ex_hello_world.c
  examples/lt_ex_hw_wallet.c
  examples/lt_ex_macandd.c
  hal/port/unix/lt_port_raspberrypi_wiringpi.c
  hal/port/unix/lt_port_unix.c
  hal/port/unix/lt_port_unix_tcp.c
  hal/port/unix/lt_port_unix_usb_dongle.c
  src/libtropic.c
  src/lt_asn1_der.c
  src/lt_l1.c
  src/lt_l3.c
  tests/functional/README.md
  tests/functional/lt_test_common.c
  tests/functional/lt_test_ire_pairing_key_slots.c
  tests/functional/lt_test_ire_write_i_config.c
  tests/functional/lt_test_rev_ecc_key_generate.c
  tests/functional/lt_test_rev_ecc_key_store.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_erase_r_config.c
  tests/functional/lt_test_rev_ping.c
  tests/functional/lt_test_rev_r_mem.c
  tests/functional/lt_test_rev_random_value_get.c
  tests/functional/lt_test_rev_read_cert_store.c
  tests/functional/lt_test_rev_read_chip_id.c
  tests/functional/lt_test_rev_read_i_config.c
  tests/functional/lt_test_rev_read_r_config.c
  tests/functional/lt_test_rev_sleep_req.c
  tests/functional/lt_test_rev_write_r_config.c
Labels: enhancement

#181 Add mcounter test
  CHANGELOG.md
  CMakeLists.txt
  include/libtropic_functional_tests.h
  src/libtropic.c
  src/lt_l3.c
  src/lt_l3_process.c
  src/lt_l3_process.h
  tests/functional/lt_test_rev_mcounter.c
Labels: functional tests

#195 Refactor device handling example test compilation
  CMakeLists.txt
  examples/lt_ex_fw_update.c
  examples/lt_ex_hello_world.c
  examples/lt_ex_hello_world_separate_API.c
  examples/lt_ex_hw_wallet.c
  examples/lt_ex_macandd.c
  hal/port/unix/lt_port_unix_tcp.c
  include/libtropic_examples.h
  include/libtropic_functional_tests.h
  include/libtropic_port.h
  tests/functional/README.md
  tests/functional/lt_test_ire_pairing_key_slots.c
  tests/functional/lt_test_ire_write_i_config.c
  tests/functional/lt_test_rev_ecc_key_generate.c
  tests/functional/lt_test_rev_ecc_key_store.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_erase_r_config.c
  tests/functional/lt_test_rev_handshake_req.c
  tests/functional/lt_test_rev_mac_and_destroy.c
  tests/functional/lt_test_rev_mcounter.c
  tests/functional/lt_test_rev_ping.c
  tests/functional/lt_test_rev_r_mem.c
  tests/functional/lt_test_rev_random_value_get.c
  tests/functional/lt_test_rev_read_cert_store.c
  tests/functional/lt_test_rev_read_chip_id.c
  tests/functional/lt_test_rev_read_i_config.c
  tests/functional/lt_test_rev_read_r_config.c
  tests/functional/lt_test_rev_resend_req.c
  tests/functional/lt_test_rev_sleep_req.c
  tests/functional/lt_test_rev_startup_req.c
  tests/functional/lt_test_rev_write_r_config.c
  tests/model_based_project/main.c
Labels: enhancement, functional tests, examples

#197 Conflicting macros (AC)
  include/bits.h
Labels: bug

#200 ETR01SDK-168: Erase R config before writing it in HW wallet example
  examples/lt_ex_hw_wallet.c
Labels: examples

#202 ETR01SDK-168: move model_based_project/ outside of tests/
  .github/workflows/integration_tests.yml
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  scripts/model_test_runner.py
  tests/README.md
  tests/model_based_project/README.md
  tests/model_based_project/compile_tests.sh
  tests/model_based_project/model_logging_cfg.yml
  tropic01_model/CMakeLists.txt
  tropic01_model/README.md
  tropic01_model/create_model_cfg.py
  tropic01_model/main.c
Labels: enhancement

#210 doc(port-unix-usb-dongle): fixed comments.
  hal/port/unix/lt_port_unix_usb_dongle.c
Labels: documentation

#214 ETR01SDK-167: Change parameter type of buff in lt_port_random_bytes to void*
  CHANGELOG.md
  examples/lt_ex_macandd.c
  hal/port/stm32/lt_port_stm32_nucleo_f439zi.c
  hal/port/stm32/lt_port_stm32_nucleo_l432kc.c
  hal/port/unix/lt_port_unix_spi.c
  hal/port/unix/lt_port_unix_tcp.c
  hal/port/unix/lt_port_unix_usb_dongle.c
  include/libtropic_functional_tests.h
  include/libtropic_port.h
  src/lt_l3.c
  src/lt_random.c
  src/lt_random.h
  tests/functional/lt_test_ire_write_i_config.c
  tests/functional/lt_test_rev_ecdsa_sign.c
  tests/functional/lt_test_rev_eddsa_sign.c
  tests/functional/lt_test_rev_mac_and_destroy.c
  tests/functional/lt_test_rev_mcounter.c
  tests/functional/lt_test_rev_ping.c
  tests/functional/lt_test_rev_r_mem.c
  tests/functional/lt_test_rev_random_value_get.c
  tests/functional/lt_test_rev_write_r_config.c
Labels: enhancement

#213 ETR01SDK-87: implement fw update for bootloader v2.0.1 acab
  CMakeLists.txt
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_0_3_1/fw_CPU_0_3_1.h
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_0_3_1/fw_SPECT_0_3_1.h
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_0_3_1/fw_v0.3.1_signed.bin
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_0_3_1/spect_app-v0.3.1_signed.bin
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_1_0_0/fw_CPU.h
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_1_0_0/fw_SPECT.h
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_1_0_0/fw_v1.0.0_signed.bin
  TROPIC01_fw_update_files/boot_v_1_0_1/fw_v_1_0_0/spect_app-v1.0.0_signed.bin
  TROPIC01_fw_update_files/boot_v_2_0_1/fw_v_1_0_0/fw_CPU.h
  TROPIC01_fw_update_files/boot_v_2_0_1/fw_v_1_0_0/fw_SPECT.h
  TROPIC01_fw_update_files/boot_v_2_0_1/fw_v_1_0_0/fw_v1.0.0.hex32_signed_chunks.bin
  TROPIC01_fw_update_files/boot_v_2_0_1/fw_v_1_0_0/spect_app-v1.0.0_signed_chunks.bin
  TROPIC01_fw_update_files/convert.py
  examples/lt_ex_fw_update.c
  examples/lt_ex_show_chip_id_and_fwver.c
  hal/port/stm32/lt_port_stm32_nucleo_f439zi.c
  hal/port/stm32/lt_port_stm32_nucleo_l432kc.c
  include/libtropic.h
  include/libtropic_common.h
  include/libtropic_examples.h
  src/libtropic.c
  src/lt_l2_api_structs.h
Labels: feature

#231 ETR01SDK-209: Github issue 228
  tests/functional/lt_test_rev_startup_req.c
Labels: enhancement

#230 ETR01SDK-190: Add flag for not checked return values, fix errors
  cmake/strict_compile_flags.cmake
  hal/port/unix/lt_port_unix_spi.c
  hal/port/unix/lt_port_unix_usb_dongle.c
  include/libtropic_common.h
  src/libtropic.c
  src/lt_aesgcm.h
  src/lt_asn1_der.h
  src/lt_crc16.h
  src/lt_ecdsa.h
  src/lt_ed25519.h
  src/lt_l1.c
  src/lt_l1.h
  src/lt_l1_port_wrap.h
  src/lt_l2_frame_check.h
  src/lt_l3_process.h
  src/lt_random.h
  tests/functional/lt_test_rev_resend_req.c
  tests/functional/lt_test_rev_startup_req.c
Labels: enhancement

#235 ETR01SDK-142: Fix errors from CodeChecker report
  scripts/codechecker/README.md
  scripts/codechecker/codechecker_build.sh
  src/libtropic.c
  src/lt_asn1_der.c
Labels: bug, enhancement

#236 ETR01SDK-199: docs(doxygen): fix typos, formatting, missing doxygen stuff
  docs/Doxyfile.in
  docs/index.md
  include/libtropic.h
  include/libtropic_common.h
  include/libtropic_examples.h
  include/libtropic_functional_tests.h
  include/libtropic_port.h
  include/lt_l2.h
  include/lt_l3.h
  src/lt_asn1_der.c
  src/lt_asn1_der.h
  src/lt_l1.h
  src/lt_l1_port_wrap.h
  src/lt_l2_api_structs.h
  src/lt_l2_frame_check.h
  src/lt_l3_api_structs.h
  src/lt_l3_process.h
Labels: documentation

#242 ETR01SDK-218: lt_r_mem_data_write: check if data size is atleast 1B
  include/libtropic.h
  include/libtropic_common.h
  include/lt_l3.h
  src/libtropic.c
  src/lt_l3.c
  tests/functional/lt_test_rev_r_mem.c
Labels: bug

#243 ETR01SDK-197: move unused macro to libtropic_macros.h
  hal/port/stm32/lt_port_stm32_nucleo_f439zi.c
  hal/port/stm32/lt_port_stm32_nucleo_l432kc.c
  hal/port/unix/lt_port_unix_spi.c
  hal/port/unix/lt_port_unix_tcp.c
  hal/port/unix/lt_port_unix_usb_dongle.c
  include/libtropic_common.h
  include/libtropic_macros.h
  src/libtropic.c
  src/lt_hkdf.c
  src/lt_l1.c
Labels: enhancement

#244 Fix (regression) : Add preprocessor switches for differences between …
  tests/functional/lt_test_rev_get_info_req_bootloader.c
  tests/functional/lt_test_rev_startup_req.c
Labels: functional tests
